### ISSUE TITLE
Profile Error:  PiPresents:  The two monitors must not overlap in Screen Config Utility

### ISSUE THREAD

**Issue by ecord17** [KenT2/pipresents-beep#60]
I have a touch screen and a HMDI screen to run the video. I am getting this error when attempting to run it. This is a raspberry pi 4 with the OS buster. I went into the ppweb editor to make sure that the video played on the HDMI0 and the touchscreen would be on HDMI1.  Or did I do this wrong.?  Any help would be appreciated.

Thank you

**Comment by KenT2** [comment]
I expect your problem is that the OS is configured so that the two displays are one on top of the other instead of being side by side. To change this 

1) Open the Applications Menu by clicking the Raspberry Pi icon on the top left of the Task Bar.

2) Move down to Preferences and select Screen Configuration in the pop-out menu.

Drag the displays until HDMI0 is to the left and HDMI1 is to the right.
